### PR TITLE
perlxs function macro, subcrate refactor

### PR DESCRIPTION
**Pull request by dnorman**
* Implement perlxs function macro - allows for additional flexibility in argument unpacking, and more idiomatic function authoring
* Reorganize subcrates to be more tidy
* Update test cases to use new perlxs function macro

This PR replaces #21 

Known issue:
If arguments are unpacked, AND context object is desired, the &mut Context must be the final argument of the subroutine, otherwise it will experience a double mutable borrow. Does the context object need to be mutable, or does it utilize interior mutability?

### CODE REVIEW

**Comment by dnorman** [comment]
@vickenty This is kind of a large change, but I feel it would be an improvement overall.
As mentioned in #21 this change stemmed from my need to be able to handle optional arguments in order to port existing perl code to rust without having to change the interface. It is also more flexible in cases of types which need to unpack multiple arguments from the stack. Module bootstrapping is handled very differently now, with registration being performed at library load time, which is an unfortunate necessity due to incremental compilation defeating attempts to maintain state across multiple macro invocations. I made sure that the xs! macro is still functional under the new module registration guts for compatibility sake. One side effect of this is that one `boot_Foo` function is exported for every package declaration, not just the root. This could potentially be removed, but I think it might be nice to allow folks to load subsets of the library.

Would you be able to offer your opinion of the changes?

FYI I am out of time for the night to fix the small conflict here. I will rebase, and push as soon as I can.

**Comment by dnorman** [comment]
Hmm... Seems like the function pointer type changes depending on which perl is being used? Do you have any insight into this @vickenty? It's compiling fine on my machine, but travisci isn't happy. I can dig into this more this week, but perhaps you could shed some light on the issue.

**Comment by dnorman** [comment]
@vickenty Candidly, I'm not sufficiently familiar with the generated code to immediately understand why the cargo tests are failing here. The `make test` seems to be working fine though. Might you have any insight as to why? This issue doesn't seem to occur for master, but I can't conceive of what changed that could cause `cc` to fail with ```= note: Undefined symbols for architecture x86_64:
            "_Perl_sv_free2", referenced from:
                _S_SvREFCNT_dec in libperl_sys-e0dc2412e62c54c5.rlib(perl_sys.o)
                _S_SvREFCNT_dec_NN in libperl_sys-e0dc2412e62c54c5.rlib(perl_sys.o)
```

**Comment by vickenty** [comment]
Sorry for taking so long to review this. This was a massive undertaking, and looks really cool. I like the idea of bindings generator for perl.

But I'm afraid that I can't accept this.

First, this seems to aim at a higher level of abstraction that perl-xs does. The new style of writing functions is no longer to interface with the XS API, but shifts focus towards writing pure rust code. This is okay by itself, just not what this crate tries to achieve.

Second thing is new dependencies. When I started this, I wanted perl-xs to be light, and it didn't change. Proc macro machinery is huge (compared to the rest of the code). `ctor`, while not big, only supports rust's tier1 targets, which is rather unfortunate.

So while I don't think this fits into perl-xs, it would be great as a separate crate.

**Comment by dnorman** [comment]
Hey @vickenty, my apologies for the laggard response here.

Thank you for explaining your feelings on the matter. I certainly understand the concern with `ctor`
Candidly, I'm not in love with that approach either. I was searching for a better way to do it, but this seemed reasonable at the time.

For what it's worth, I don't think this kind of automatic package registration is the most important part of the code in question, and I would be perfectly happy to use a version which restored the previous style. 

_As an aside: I would like to mention that the registration of multiple bootstrap functions was intentional, such that the same .so file could in theory satisfy different formulations of `require` statements. This could understandably be seen as a either desirable feature, or as a messy implementation detail._

Regarding the proc macro machinery, I would like to point out that it is already included for perlxs_derive / perlxs_derive_internals, and even if it weren't, I would respectfully question the utility of avoiding the proc macro system for reasons of compile-time overhead. I would further like to point out that the xs!{ sub } macro functionality need not necessarily be deprecated by this change necessarily. 

The goal of this change was not to arbitrarily prefer proc macros, but rather to address a need to support subroutines with optional positional arguments, unpack key/value pair arguments, and arguments which differ based on prior arguments. I could not figure out how to achieve any of those under the macro_rules macro system. 

While those subroutine interface contracts may (rightly) be considered bad practice – for better or for worse they are very common in real-world use cases. When porting code from perl to rust, and trying to avoid breaking existing code/test cases, it can be necessary to match existing interface definitions exactly. I suspect that these changes could potentially also help a lot of folks in similar situations who are looking to port meaningful portions of their perl stacks to rust.

With that, I would like to ask if you would you be willing to consider merging a changed version which removed the ctor dependency and retaining the bootstrap/use directives. Do you think that might be reasonable?

Either way, thank you for all your hard work in developing this library. I appreciate you! 🌻

**Comment by dnorman** [comment]
cc @schellj

**Pull request closed without merging**
