### PR TITLE
Subcrate cleanups

### PR DESCRIPTION
**Pull request by dnorman**
* Reorganize existing subcrates in the style of the wasm_bindgen subcrate layout (which seems to be the new hotness) in preparation for the introduction of additional subcrates for `#[perlxs]` function attribute macro.

* Relicense subcrates to match current best-practice: dual-license MIT/Apache-2.0

* update main perl-xs crate to export macros without having to directly use the subcrate

^_^

### CODE REVIEW

**Comment by dnorman** [comment]
Rebased on master, because #19 was merged

**Comment by vickenty** [comment]
Sorry for the long wait. Thank you for the effort, but I don't think I agree to any of the changes proposed here.

I think it is better to keep everything under the same license. And if changing license, it might be better to re-license everything (perl-sys too) under Per's artistic license, for maximum compatibility. Would you agree with that?

I can't seem to convince myself to like the new crate layout either. Let's punt on this until we have more crates to play with? And perhaps derive and derive_internals crates can be merged too.

Finally, re-exporting the macro adds its dependencies to the main crate, even if the user does not use the macro in their crate. I think it should at least be a feature, like in serde.

**Comment by dnorman** [comment]
Regarding the license, my intention was that this might spur a discussion for changing the license for the parent crate as well, such that they were all MIT/Apache2.

In my view, the implications of a license change to MIT/Apache2 are more or less the same as the existing license. Published crates on crates.io are overwhelmingly licensed this way. See: https://gist.github.com/passcod/2e1983ce415b32bdf3a0

All things being equal, I don't see a compelling reason why this should differ from the norm. That said, ultimately as long as it's not a copyleft license, I don't feel sufficiently strongly to press the issue further, and will excise the license change from this PR at your request.

The new crate layout is inspired by https://github.com/rustwasm/wasm-bindgen/tree/master/crates which would seem to be the most current example of best practices as set by the rust core team that I can find on the topic. It seems to be the style to keep the proc_macro crate as light as possible, and to manage the machinery of codegen in a separate crate. This will make a little bit more sense when I finish the function macro stuff.

Regarding a feature flag, I don't have any objection to doing that, however I would prefer to include the batteries as much as possible to help new users adapt as painlessly as possible. I suspect this also will become clearer when the function macro implementation is completed. Stay tuned!

I would welcome your thoughts on any/all of the above :)

**Comment by dnorman** [comment]
Closing in favor of #23

**Pull request closed without merging**
